fine_tune_yolo_node:
    ros__parameters:
        model_path: 'weights/yellow_box_v2.pt'
        confidence: 0.750
        max_history: 5
        max_jump: 2.0
        bb_margin: 0.495

yolo_pose_node:
    ros__parameters:
        model_path: 'weights/yolo26n-pose.pt'
        confidence: 0.50

speed_det_node:
    ros__parameters:
        save_distance_mode: false
        record_mode: true
        annotations_mode: true
        alpha_smooth: 0.4
        cooldown_duration: 5.0
        speed_threshold: 1.5
        startup_grace_period: 8.0
        landing_z_threshold: 0.3
        camera_tilt_deg: 15.0
        camera_roll_deg: -90.0
        effective_gravity: 8.0
