yolo_world_node:
  ros__parameters:
    confidence: 0.50
    max_history: 5
    max_jump: 0.5
    bb_margin: 0.46
    custom_classes:
      - "bottle"

yolo_pose_node:
  ros__parameters:
      model_path: 'weights/yolo26n-pose.pt'
      confidence: 0.50

optical_tracking_node:
  ros__parameters:
    max_dist_meter: 0.25
    mask_thickness_arm: 0.4
    mask_thickness_hand: 0.25
    target_class_id: "bottle"
    debug_mask_overlay: true
    record_mode: false
    camera_roll_deg: 90.0
    camera_tilt_deg: 0.0
