yolo_world_node:
  ros__parameters:
    confidence: 0.50
    max_history: 5
    max_jump: 0.5
    bb_margin: 0.46
    custom_classes:
      - "plastic bottle"
      - "cardboard_box"
      - "alien_plushie"
      - "juice_bottle"
      - "bottle"

yolo_pose_node:
  ros__parameters:
      model_path: 'weights/yolo26n-pose.pt'
      confidence: 0.50

optical_tracking_node:
  ros__parameters:
    max_dist_meter: 20.0
    mask_thickness: 0.4